# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'food-root' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for food-root
pod 'SDWebImage', '~> 4.0'
pod 'FDFullscreenPopGesture', '~> 1.1'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'Bugly','~> 2.5.0'
pod 'CTMediator', '~> 25'

end






